'use strict';
const scenes=[
 ['THOR','01-thor','#69d8ff'],['IRON MAN','02-iron-man','#e96675'],['CAPTAIN AMERICA','03-captain-america','#5caaff'],['HULK','04-hulk','#94e869'],['LOKI','05-loki','#b2ec76'],['DOCTOR STRANGE','06-doctor-strange','#ffb979'],['SPIDER-MAN','07-spider-man','#f67f88'],['BLACK PANTHER','08-black-panther','#ab80ff'],['VIBRANIUM','09-vibranium','#7ceaff'],['THE WITCHER','10-witcher','#bcd8f1']
];
const wallpaper=document.body.classList.contains('wallpaper');
const panes=[document.querySelector('#scene-a'),document.querySelector('#scene-b')];let active=0,index=0,transitioning=false;
const title=document.querySelector('#title'),count=document.querySelector('#count');
const powerNames=['MJOLNIR / LIGHTNING','ARC REACTOR / REPULSOR','SHIELD / KINETIC TRAIL','GAMMA / SHOCKWAVE','ILLUSION / GREEN MAGIC','MYSTIC PORTAL','WEB / SWING TRAIL','VIBRANIUM SUIT / CLAWS','VIBRANIUM / ENERGY CORE','SILVER SWORD / SIGNS'];
function imagePath(file,ext){return `scenes/${file}.${ext}`}
function show(n){if(transitioning)return;transitioning=true;n=(n+scenes.length)%scenes.length;const [name,file,color]=scenes[n],img=new Image();img.onload=()=>{const next=1-active;panes[next].style.backgroundImage=`url("${img.src}")`;panes[next].classList.add('active');panes[active].classList.remove('active');active=next;index=n;title.textContent=name;count.textContent=`${String(n+1).padStart(2,'0')} / ${scenes.length} · ${powerNames[n]}`;new Image().src=imagePath(scenes[(n+1)%scenes.length][1],'jpg');transitioning=false};img.onerror=()=>{transitioning=false};img.src=imagePath(file,'jpg')}
show(0);let interval=setInterval(()=>show(index+1),5000);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(interval);interval=null}else if(!interval){interval=setInterval(()=>show(index+1),5000)}});
if(!wallpaper){
 const form=document.querySelector('#search-form'),input=document.querySelector('#search-input'),state=document.querySelector('#search-state'),help=document.querySelector('#console-help');
 const engines={google:'https://www.google.com/search?q=',bing:'https://www.bing.com/search?q=',duckduckgo:'https://duckduckgo.com/?q='};
 const buttons=[...document.querySelectorAll('[data-engine]')];
 let engine=localStorage.getItem('avenger-search-engine');if(!engines[engine])engine='google';
 function selectEngine(value){engine=value;localStorage.setItem('avenger-search-engine',value);buttons.forEach(b=>{const selected=b.dataset.engine===value;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected?'true':'false')});state.textContent=value.toUpperCase()+' READY'}
 buttons.forEach(b=>b.addEventListener('click',()=>{selectEngine(b.dataset.engine);input.focus()}));selectEngine(engine);
 function parse(value){let query=value.trim(),target=engine;const direct=query.match(/^\/(g|b|d)\s+(.+)$/i);if(direct){target={g:'google',b:'bing',d:'duckduckgo'}[direct[1].toLowerCase()];query=direct[2].trim()}return {query,target}}
 form.addEventListener('submit',e=>{e.preventDefault();const {query,target}=parse(input.value);if(query)location.href=engines[target]+encodeURIComponent(query)});
 document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==input&&!e.ctrlKey&&!e.altKey&&!e.metaKey){e.preventDefault();input.focus()}if(e.key==='Escape'&&document.activeElement===input){input.value='';input.blur()}});
 input.addEventListener('input',()=>{const {query,target}=parse(input.value);help.textContent=query?`↗ SEARCH ${target.toUpperCase()} FOR “${query.slice(0,55)}”`:'ENTER TO SEARCH · / TO FOCUS · /g /b /d TO OVERRIDE'});
 const mic=document.querySelector('#voice-button'),Recognizer=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!Recognizer){mic.hidden=true}else{mic.addEventListener('click',()=>{const rec=new Recognizer();rec.lang=navigator.language||'en-US';rec.interimResults=false;rec.maxAlternatives=1;mic.classList.add('listening');state.textContent='LISTENING…';rec.onresult=e=>{input.value=e.results[0][0].transcript;input.dispatchEvent(new Event('input'));input.focus();state.textContent='VOICE CAPTURED'};rec.onerror=()=>{state.textContent='MICROPHONE UNAVAILABLE'};rec.onend=()=>mic.classList.remove('listening');try{rec.start()}catch{mic.classList.remove('listening');state.textContent='MICROPHONE UNAVAILABLE'}})}
}
const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');let w=0,h=0,dpr=1,stars=[];function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(125,Math.ceil(w*h/15000))},()=>({x:Math.random()*w,y:Math.random()*h,r:.35+Math.random()*1.5,v:.08+Math.random()*.25,a:.15+Math.random()*.55,p:Math.random()*7}))}addEventListener('resize',resize);resize();function frame(t){if(!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches){ctx.clearRect(0,0,w,h);for(const s of stars){s.y-=s.v;if(s.y<-4){s.y=h+4;s.x=Math.random()*w}ctx.fillStyle=`rgba(180,225,255,${s.a*(.7+.3*Math.sin(t*.001+s.p))})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
