'use strict';
const scenes=[
 ['THOR','01-thor','#69d8ff'],['IRON MAN','02-iron-man','#e96675'],['CAPTAIN AMERICA','03-captain-america','#5caaff'],['HULK','04-hulk','#94e869'],['LOKI','05-loki','#b2ec76'],['DOCTOR STRANGE','06-doctor-strange','#ffb979'],['SPIDER-MAN','07-spider-man','#f67f88'],['BLACK PANTHER','08-black-panther','#ab80ff'],['VIBRANIUM','09-vibranium','#7ceaff'],['THE WITCHER','10-witcher','#bcd8f1']
];
const wallpaper=document.body.classList.contains('wallpaper');
const panes=[document.querySelector('#scene-a'),document.querySelector('#scene-b')];let active=0,index=0,transitioning=false;
const art=document.querySelector('#art'),title=document.querySelector('#title'),count=document.querySelector('#count');
function imagePath(file,ext){return `scenes/${file}.${ext}`}
function show(n){if(transitioning)return;transitioning=true;n=(n+scenes.length)%scenes.length;const [name,file,color]=scenes[n],img=new Image();img.onload=()=>{const next=1-active;panes[next].style.backgroundImage=`url("${img.src}")`;panes[next].classList.add('active');panes[active].classList.remove('active');active=next;index=n;art.classList.remove('enter');art.src=imagePath(file,'svg');art.style.setProperty('--accent',color);title.textContent=name;count.textContent=`${String(n+1).padStart(2,'0')} / ${scenes.length}`;requestAnimationFrame(()=>art.classList.add('enter'));new Image().src=imagePath(scenes[(n+1)%scenes.length][1],'jpg');transitioning=false};img.onerror=()=>{transitioning=false};img.src=imagePath(file,'jpg')}
show(0);let interval=setInterval(()=>show(index+1),5000);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(interval);interval=null}else if(!interval){interval=setInterval(()=>show(index+1),5000)}});
if(!wallpaper){const form=document.querySelector('#search-form');form.addEventListener('submit',e=>{e.preventDefault();const q=form.querySelector('input').value.trim();if(q)location.href='https://www.google.com/search?q='+encodeURIComponent(q)})}
const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');let w=0,h=0,dpr=1,stars=[];function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(125,Math.ceil(w*h/15000))},()=>({x:Math.random()*w,y:Math.random()*h,r:.35+Math.random()*1.5,v:.08+Math.random()*.25,a:.15+Math.random()*.55,p:Math.random()*7}))}addEventListener('resize',resize);resize();function frame(t){if(!document.hidden&&!matchMedia('(prefers-reduced-motion: reduce)').matches){ctx.clearRect(0,0,w,h);for(const s of stars){s.y-=s.v;if(s.y<-4){s.y=h+4;s.x=Math.random()*w}ctx.fillStyle=`rgba(180,225,255,${s.a*(.7+.3*Math.sin(t*.001+s.p))})`;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
